Add support for intel-quark ZE250
resin-os/resin-intel-quark pull request #1
Opened 2016-10-25 17:53 UTC by telphan

@agherzan @floion

2016-10-26 10:42 UTC, agherzan commented
Typo: "resin-init-flasher: Configure the flsaher type"

2016-10-26 10:48 UTC, agherzan commented
Typo: "grub-efi: Provide frub configuration files for internal and external use"

2016-10-26 10:56 UTC, agherzan commented
"layers: Add supporting layers (i.e. submodules)" should be rephrased as it doesn't only add layers (see resin-yocto-scripts).

2016-10-26 10:56 UTC, agherzan requested changes

2016-10-26 10:56 UTC, agherzan commented on .gitignore
> +conf-notes.txt
Please add a new line

2016-10-26 10:56 UTC, agherzan commented on layers/meta-resin-intel-quark/recipes-core/images/resin-image.bbappend
> +    core-image-minimal-initramfs-intel-quark.cpio.gz:/initramfs \
Could you please add some explanation why we need an initramfs?

2016-10-26 10:56 UTC, agherzan commented on layers/meta-resin-intel-quark/recipes-core/initrdscripts/files/init-external-media.sh
> +PATH=/sbin:/bin:/usr/sbin:/usr/bin
Isn't this the same script used for nuc? Can we abstract this into a meta-resin feature? As well, why do we need the initramfs in normal images? Does it boot from usb or from the internal device?

2016-10-26 10:56 UTC, agherzan commented on layers/meta-resin-intel-quark/recipes-containers/docker-disk/docker-resin-supervisor-disk.bbappend
> +SUPERVISOR_REPOSITORY = "resin/i386-supervisor"
CC https://github.com/resin-os/resinos/issues/102

2016-10-26 10:56 UTC, agherzan commented on layers/meta-resin-intel-quark/recipes-devtools/go/files/0002-implement-atomic-quadword-ops-with-FILD-FISTP.patch
> +
Lacking upstream status tag.

2016-10-26 10:56 UTC, agherzan commented on layers/meta-resin-intel-quark/recipes-devtools/go/files/0001-Revert-runtime-check-and-fail-early-with-a-message-i.patch
> +
Lacking upstream status tag.

2016-10-26 10:56 UTC, agherzan commented on layers/meta-resin-intel-quark/recipes-devtools/go/go-cross_%.bbappend
> +    file://0001-Revert-runtime-check-and-fail-early-with-a-message-i.patch \
I'm wondering if these patches should not go in meta-resin and then only activate them if mmx is not available on the board. In this way multiple boards in the future will be able to benefit from it. @floion , what do you think?

2016-10-26 11:49 UTC, telphan commented on layers/meta-resin-intel-quark/recipes-devtools/go/files/0002-implement-atomic-quadword-ops-with-FILD-FISTP.patch
> +
Fixing.

2016-10-26 11:49 UTC, telphan commented on layers/meta-resin-intel-quark/recipes-devtools/go/files/0001-Revert-runtime-check-and-fail-early-with-a-message-i.patch
> +
Fixing.

2016-10-26 11:53 UTC, telphan commented on layers/meta-resin-intel-quark/recipes-core/initrdscripts/files/init-external-media.sh
> +PATH=/sbin:/bin:/usr/sbin:/usr/bin
This is not the same script as the nuc, chances are this might work for nuc too, but not the other way around. All testing was done on usb, but the device should boot from internal medium. I will try to see if I can get rid of the initramfs from emmcs.

2016-10-26 11:53 UTC, telphan commented on layers/meta-resin-intel-quark/recipes-core/images/resin-image.bbappend
> +    core-image-minimal-initramfs-intel-quark.cpio.gz:/initramfs \
I will add an explanation.

2016-10-26 11:53 UTC, telphan commented on .gitignore
> +conf-notes.txt
Ok.

2016-10-31 13:20 UTC, agherzan commented
This needs to be blocked until supervisor is fixed for x87.

2016-11-09 09:23 UTC, michal-mazurek commented on layers/meta-resin-intel-quark/README.md
> +This repository enables building resin.io for intel-quark
"resin.io" should be upper case

2016-11-09 09:31 UTC, telphan commented on layers/meta-resin-intel-quark/README.md
> +This repository enables building resin.io for intel-quark
I have only seen it written in lower case. Marked as NIT

2016-11-09 11:00 UTC, agherzan approved these changes

2016-11-09 13:35 UTC, merged