Fix go cross
resin-os/resin-intel-quark pull request #6
Opened 2016-11-29 12:25 UTC by telphan

@agherzan @floion @michal-mazurek

2016-11-29 12:28 UTC, floion commented on layers/meta-resin-intel-quark/recipes-devtools/go/files/0002-implement-atomic-quadword-ops-with-FILD-FISTP.patch
> -
Why this change?

2016-11-29 13:34 UTC, agherzan requested changes

2016-11-29 13:34 UTC, agherzan commented on layers/meta-resin-intel-quark/recipes-devtools/go/files/0001-Revert-runtime-check-and-fail-early-with-a-message-i.patch
> -Upstream Status: Inappropriate
Inappropriate [reason]

2016-11-29 14:35 UTC, telphan commented on layers/meta-resin-intel-quark/recipes-devtools/go/files/0002-implement-atomic-quadword-ops-with-FILD-FISTP.patch
> -
Changing....mistakes were made.

2016-11-29 14:36 UTC, agherzan commented
@telphan this needs to reference an issue

2016-11-29 14:38 UTC, telphan commented on layers/meta-resin-intel-quark/recipes-devtools/go/files/0001-Revert-runtime-check-and-fail-early-with-a-message-i.patch
> -Upstream Status: Inappropriate
Can you open an issue tab for this repo?

2016-11-29 14:38 UTC, telphan commented
Can you open an issue tab for this repo? @agherzan

2016-11-29 14:41 UTC, telphan commented on layers/meta-resin-intel-quark/recipes-devtools/go/files/0002-implement-atomic-quadword-ops-with-FILD-FISTP.patch
> -
Fixed

2016-11-29 14:50 UTC, agherzan commented
@telphan there is already an issue in resinos for this (afaik)

2016-11-29 14:51 UTC, agherzan requested changes

2016-11-29 14:51 UTC, agherzan commented on layers/meta-resin-intel-quark/recipes-devtools/go/files/0001-Revert-runtime-check-and-fail-early-with-a-message-i.patch
> +Upstream Status: Inappropriate [revert]
That is not very informative though. Here are some examples: http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines#Patch_Header_Recommendations

2016-11-29 14:52 UTC, telphan commented
Connects to resin-os/resinos#136

2016-11-29 14:55 UTC, telphan commented on layers/meta-resin-intel-quark/recipes-devtools/go/files/0001-Revert-runtime-check-and-fail-early-with-a-message-i.patch
> +Upstream Status: Inappropriate [revert]
I will just change the Status to Pending, even though if this were to be merged upstream it will require changes.

2016-11-29 15:07 UTC, telphan commented on layers/meta-resin-intel-quark/recipes-devtools/go/files/0001-Revert-runtime-check-and-fail-early-with-a-message-i.patch
> +Upstream Status: Inappropriate [revert]
Fixed

2016-11-30 17:46 UTC, agherzan approved these changes

2016-11-30 17:46 UTC, merged